[package]
name = "assistant"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deepspeech = { path="../deepspeech-rs" }
audrey = "0.3"
dasp_interpolate = { version = "0.11", features = ["linear"] }
dasp_signal = "0.11"
